# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Small World Assessment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Small World Assessment
  
  target 'Small World AssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Small World AssessmentUITests' do
    # Pods for testing
  end

end
